### ISSUE TITLE
mqconfig fails on nofile

### ISSUE THREAD

**Issue by a359089** [ibm-messaging/mq-docker#1]
My host is rhel 6.5 and it has MQ 8 installed. Starting MQ8 docker container however unsuccessfully with log:

Current User Limits (root)
  nofile       (-Hn)  4096 files                         IBM>=10240        FAIL
  nofile       (-Sn)  1024 files                         IBM>=10240        FAIL

ERROR: mqconfig returned a non-zero return code

However  host /etc/security/limits.conf file specified correct value

mqm  -  nofile  10240
root  -  nofile  10240

It appears value is taken from Ubuntu OS from docker image and I do not have access to set it?

**Comment by a359089** [comment]
OK, restart docker service picked up correct value set in host OS. Now it fails at shmmax although it's considered a warning and it's set correctly at host OS (sysctl kernel.shmmax
kernel.shmmax = 268435456)

mqconfig: V3.7 analyzing DISTRIB_ID=Ubuntu settings for WebSphere MQ V8.0

System V Semaphores
  semmsl     (sem:1)  250 semaphores                     IBM>=32           PASS
  semmns     (sem:2)  0 of 32000 semaphores      (0%)    IBM>=4096         PASS
  semopm     (sem:3)  32 operations                      IBM>=32           PASS
  semmni     (sem:4)  0 of 128 sets              (0%)    IBM>=128          PASS

System V Shared Memory
  shmmax              33554432 bytes                     IBM>=268435456    WARN
  shmmni              0 of 4096 sets             (0%)    IBM>=4096         PASS
  shmall              0 of 2097152 pages         (0%)    IBM>=2097152      PASS

System Settings
  file-max            7264 of 524288 files       (1%)    IBM>=524288       PASS

Current User Limits (root)
  nofile       (-Hn)  10240 files                        IBM>=10240        PASS
  nofile       (-Sn)  10240 files                        IBM>=10240        PASS

ERROR: mqconfig returned a non-zero return code

**Comment by arthurbarr** [comment]
Check out the section "Preparing your Docker host" in the [README](https://github.com/ibm-messaging/mq-docker/blob/master/README.md).  RHEL 6.5 doesn't have a recent enough kernel to provide the container with enough shared memory - you can get round this on older kernels by adding the `--ipc host` parameter to your `docker run` comman.  Note that this reduces the isolation of the container.

**Comment by a359089** [comment]
Yeah, that's the problem. And now container is running! Wondering why rhel6.5 has such 'old' kernel, lol. Continue on with the testing... Thx. --Will
