### ISSUE TITLE
MQ Docker on Windows 10 (native) doesn't save config

### ISSUE THREAD

**Issue by QAnders** [ibm-messaging/mq-docker#104]
I'm running the mq-docker on Windows 10 Docker (native) but it seems that any configuration I am doing is not saved to the container.
E.g. if I add a Queue and then restart the container the Queue I added is gone. The Queue will however work normally during the time the MQ container is running.

`docker start mq01`

>> Login in to WebGUI and create a local queue

`docker stop mq01`

`docker start mq01`

>> Login to WebGUI and the Queue is not there

**Comment by parrobe** [comment]
Hi @QAnders , When you say `Windows 10 Docker (native)` could you confirm that you don't mean Docker for Windows 10.

Could you provide the output of the following command `docker info` and `docker version`

**Comment by QAnders** [comment]
I am also running IBM DataPower on my Laptop and from DataPower I have shared volumes successfully so both auth and firewall is working correctly for volume mounts.

**Comment by QAnders** [comment]
Now I have a slight variation again... This time when I started the MQ container (`docker start mq01`) the previously created channel and local queues where still there but the CLAUTH() was changed/removed so I had to run the `ALTER QMGR CHLAUTH(DISABLED) CONNAUTH(' ')` command again...

**Comment by arthurbarr** [comment]
Are you using an image with MQ Advanced for Developers, and using the [default developer configuration](https://github.com/ibm-messaging/mq-docker#mq-developer-defaults) (which is on by default)?  If you are setting up your own CHLAUTH, you should probably make sure that you set `MQ_DEV` to `false`.  This might be interfering with your own configuration.

**Comment by parrobe** [comment]
This repo (mq-docker) is now deprecated and is being replaced by the [ibm-messaging/mq-container](https://github.com/ibm-messaging/mq-container) repo. Please try this new repo and see if you continue to experience the problem listed here. If you do please raise a new issue on the new repo.
