### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by AjayKumaraj** [ibm-messaging/mq-docker#108]
docker run --env LICENSE=accept  --env MQ_QMGR_NAME=QM1 --publish 1414:1414  --publish 9443:9443   --detach -v C:/doc-vol:/mnt/mqm ibmcom/mq

output:AMQ6242E: Incorrect ownership for '/var/mqm/amqmfsck.lck'. Current(0)

**Comment by parrobe** [comment]
Hi @AjayKumaraj - Could you try again use Docker volumes as detailed [here](https://github.com/ibm-messaging/mq-docker#running-with-the-default-configuration-and-a-volume)

**Comment by deivsonrayner** [comment]
I am facing this same problem when creating MQ helm realese from ICP helm ibm-mqadvanced-server-dev V1.1.0. In my case I am using persistente volume and following my logs I can see the POD successfuly claiming it

**Comment by deivsonrayner** [comment]
I have solved my problem including no_root_squash on the /etc/exports nfs configuration (rw,sync,no_subtree_check,**no_root_squash**). It sounds that root_squash was preventing changes volume files ownership.
