### ISSUE TITLE
Copyright in LICENSE is blank

### ISSUE THREAD

**Issue by timgp** [ibm-messaging/mq-docker#115]
`Copyright [yyyy] [name of copyright owner]`

https://github.com/ibm-messaging/mq-docker/blob/master/LICENSE#L190

**Comment by parrobe** [comment]
Good spot, this repo is deprecated but i will make the change to this.
 I've checked the new repo and can see the problem is there as well so i've created the following issue:

https://github.com/ibm-messaging/mq-container/issues/61
