### ISSUE TITLE
Authorization failure while running latest MQ on Linux Mint

### ISSUE THREAD

**Issue by cdorot** [ibm-messaging/mq-docker#125]
While running a mq with version **9.1.1.0**, I get an **AMQ7077E**: You are not authorized to perform the requested operation (You can see below the full log)
With **9.0.5.0** version of mq, it succeeds.

My OS is Linux Mint 19 (Tara).
Used version of Docker : 18.09.1, build 4c52b90
Used version of docker-compose : 1.23.1, build b02f1306

Could you see what is wrong with the latest version ?

> $ docker-compose up mq
> Creating docker-utils_mq_1_82891acb31bd ... done
> Attaching to docker-utils_mq_1_584f1f5a50a0
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.749Z Set password for "admin" user
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.755Z Using queue manager name: QM1
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.757Z CPU architecture: amd64
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.757Z Linux kernel version: 4.15.0-43-generic
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.757Z Container runtime: docker
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.757Z Base image: Ubuntu 16.04.5 LTS
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.757Z Maximum file handles: 1590022
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.757Z Running as user ID 0 (root) with primary group 0, and supplementary groups 999
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.758Z MQM user ID 999 (mqm) has primary group 999, and supplementary groups 
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.758Z Capabilities (bounding set): chown,dac_override,fowner,fsetid,kill,setgid,setuid,setpcap,net_bind_service,net_raw,sys_chroot,mknod,audit_write,setfcap
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.758Z seccomp enforcing mode: filtering
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.758Z Process security attributes: docker-default (enforce)
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.758Z No volume detected. Persistent messages may be lost
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.764Z Created directory structure under /var/mqm
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.764Z Image created: 2018-12-10T11:14:11+00:00
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.764Z Image revision: 4145f077b6210c1856fd834abad1a2f016d5862f
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.764Z Image source: https://github.com/ibm-messaging/mq-container.git
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.773Z MQ version: 9.1.1.0
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.773Z MQ level: p911-L181121.DE
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.773Z MQ license: Developer
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.774Z Creating queue manager QM1
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.774Z Starting web server
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.774Z Error -1 starting web server: 
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.779Z crtmqm returned 119
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.779Z AMQ7077E: You are not authorized to perform the requested operation.
> mq_1_584f1f5a50a0 | 
> mq_1_584f1f5a50a0 | 2019-01-15T16:46:05.779Z [/usr/bin/crtmqm: exit status 11

9]

**Comment by arthurbarr** [comment]
It looks like this issue should have been raised in the [mq-container](https://github.com/ibm-messaging/mq-container) repository.  An exit status of 119 from [crtmqm](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.ref.adm.doc/q083120_.htm) is a Windows authorization error.

Could you perhaps raise a new issue on the `mq-container` repo, including your Docker Compose file?
