### ISSUE TITLE
MQ Custom Image Example Error - MQM Group Not Found

### ISSUE THREAD

**Issue by monctonProgrammer** [ibm-messaging/mq-docker#130]
**Description:** Getting the following error when running a docker build. I thought mqm group would be automatically created by default. Doesn't mention otherwise in the site link below. Can someone else try this?

System Notes:(VS Code- Docker build), windows machine.

Error: useradd: group 'mqm' does not exist

https://github.com/ibm-messaging/mq-docker/blob/master/README.md#customizing-the-queue-manager-configuration

System Notes:(VS Code- Docker build), windows machine.

```
Docker File:
FROM ibmcom/mq
USER root
RUN useradd alice -G mqm && \
    echo alice:passw0rd | chpasswd
USER mqm
COPY 20-config.mqsc /etc/mqm/
```

**Comment by parrobe** [comment]
This GitHub repository is now deprecated and no longer accepting issues or Pull Requests. Please look at [mq-container](https://github.com/ibm-messaging/mq-container)
