### ISSUE TITLE
MQ Data volumn container 

### ISSUE THREAD

**Issue by elewis787** [ibm-messaging/mq-docker#19]
Has anyone tried mounting the /var/mqm in a data volume container ? 

I am running into issue. 
My MQ install works if I mount a volume from my host but I was hoping to use a data volume container for portability. 

Any advice / help would get great 

This is what i have so far : 
RUN groupadd --gid 1000 mqm
RUN useradd --uid 1000 --gid mqm --home-dir /var/mqm mqm

#Create /var/mqm dir
RUN mkdir -p /var/mqm
RUN mkdir -p /opt/mqm

#take ownership
RUN chown -R mqm:mqm /var/mqm
RUN chown -R mqm:mqm /opt/mqm

VOLUME ["/opt/mqm/","/var/mqm"]

#switch to mqm user
USER mqm

#tell us this is the mqm data container
CMD ["echo","Data container for mqm"]

**Comment by arthurbarr** [comment]
You just need to remove `/opt/mqm` from the `VOLUME` line.  This is causing the empty `/opt/mqm` directory from your volume to be mounted in the MQ container, which wipes out the MQ install.

Alternatively, to perhaps make things simpler, you can just re-use your `mq` image for the data volume container, overriding the entrypoint:

```
docker create -v /var/mqm --name mqdata --entrypoint=/bin/true mq
docker run -d -e LICENSE=accept -e MQ_QMGR_NAME=QM1 -p 1414:1414 --volumes-from mqdata mq
```

You can check this is working by creating another container using the same volume, as shown below:
```
docker run -ti --volumes-from mqdata ubuntu:14.04 ls /var/mqm/qmgrs
```

I'll close this issue now, but please just re-open it if this doesn't work for you.

**Comment by elewis787** [comment]
Thanks a lot for the help ! Works great.
