### ISSUE TITLE
shmmax too small

### ISSUE THREAD

**Issue by per2jensen** [ibm-messaging/mq-docker#2]
I am trying out the supplied docker image on an Ubuntu 14.04 desktop machine.

Docker version:
============
docker --version
Docker version 1.5.0, build a8a31ef

Dockerfile:
==========
FROM ibmimages/mqadvanced
RUN useradd  pj -G mqm && \
    echo pj:passw0rd | chpasswd
COPY config.mqsc /etc/mqm/
RUN echo "kernel.shmmax=268435456" >> /etc/sysctl.conf

Running the image:
==================
docker run   --env LICENSE=accept   --env MQ_QMGR_NAME=QM1   --volume /var/example:/var/mqm   --publish 1414:1414  mymq
----------------------------------------
Name:        WebSphere MQ
Version:     8.0.0.2
Level:       p800-002-150303.DE
BuildType:   IKAP - (Production)
Platform:    WebSphere MQ for Linux (x86-64 platform)
Mode:        64-bit
O/S:         Linux 3.13.0-44-generic
InstName:    Installation1
InstDesc:    
Primary:     No
InstPath:    /opt/mqm
DataPath:    /var/mqm
MaxCmdLevel: 801
LicenseType: Developer
----------------------------------------
mqconfig: V3.7 analyzing Ubuntu 14.04.2 LTS settings for WebSphere MQ V8.0

System V Semaphores
  semmsl     (sem:1)  250 semaphores                     IBM>=32           PASS
  semmns     (sem:2)  0 of 32000 semaphores      (0%)    IBM>=4096         PASS
  semopm     (sem:3)  32 operations                      IBM>=32           PASS
  semmni     (sem:4)  0 of 128 sets              (0%)    IBM>=128          PASS

System V Shared Memory
  shmmax              33554432 bytes                     IBM>=268435456    WARN
  shmmni              0 of 4096 sets             (0%)    IBM>=4096         PASS
  shmall              0 of 2097152 pages         (0%)    IBM>=2097152      PASS

System Settings
  file-max            12352 of 1624620 files     (0%)    IBM>=524288       PASS

Current User Limits (root)
  nofile       (-Hn)  1048576 files                      IBM>=10240        PASS
  nofile       (-Sn)  524288 files                       IBM>=10240        PASS

ERROR: mqconfig returned a non-zero return code

I guess the SHMMAX warning is causing the problem. Therefore I tried to alter the value this way in the Dockerfile:
RUN echo "kernel.shmmax=268435456" >> /etc/sysctl.conf
the rebuilding and running the image. Still no go.

From what I read on the net, there might be a problem altering the kernel settings in the image. 

Any ideas ?

**Comment by arthurbarr** [comment]
Check out the section "Preparing your Docker host" in the [README](https://github.com/ibm-messaging/mq-docker#preparing-your-docker-host).  Note that just upgrading to Ubuntu 14.04.2 might not be enough - you'll need to [upgrade your kernel](https://help.ubuntu.com/community/Kernel/Upgrade) as well (or use `--ipc host` on your `docker run` if you don't want to mess with the kernel).

**Comment by per2jensen** [comment]
Thank you.
I was indeed not up to Ubuntu 14.04.2 - MQ is running now.
