### ISSUE TITLE
mq v9?

### ISSUE THREAD

**Issue by davidkarlsen** [ibm-messaging/mq-docker#21]
Will you upgrade / create a branch for v9 as well?

**Comment by arthurbarr** [comment]
Yes, we're going to do that.  Although this sample hasn't been updated yet, MQ V9 is still supported in Docker.

**Comment by arthurbarr** [comment]
There is now a sample of an MQ V9 queue manager in Docker, and the corresponding image is available on Docker Hub: [ibmcom/mq:9](https://hub.docker.com/r/ibmcom/mq)
