### ISSUE TITLE
Container entrypoint should tail qmgr logs to stdout

### ISSUE THREAD

**Issue by dnwe** [ibm-messaging/mq-docker#26]
Currently the container outputs startup information as it configures the QM and then just shows the output of `dspmq`.

It would be helpful if the entrypoint instead did a `tail -F /var/mqm/errors/AMQERR01.LOG /var/mqm/qmgrs/${MQ_QMGR_NAME}/errors/AMQERR01.LOG}` so that the qmgr and service eventlog was output to stdout and hence visible via `docker logs`

**Comment by arthurbarr** [comment]
There are a few reasons why I didn't originally do this:

1. It would cause the contents of `AMQERR01.LOG` to be duplicated on the filesystem: once in `/var/mqm`, and once in the Docker logs (which are also persisted to disk, naturally)
2. The Docker console log would contain a mix of Docker-specific messages, and MQ-specific messages.  This could make the logs more difficult to understand, and also present problems for log parsing.
3. We would need some extra tests to ensure that log rotation to `AMQERR02.LOG` was handled correctly.

None of these are necessarily deal-breakers, but need to be considered before making any changes.

**Comment by frank-wagner-azd** [comment]
this would duplicate a lot of Output 
if realized, this should be done optional

**Comment by parrobe** [comment]
We'd also have problems where MQ prints out 13 lines for each single message in the `AMQERR1.LOG` so something like Queue Manager startup would quickly swamp the docker logs.

**Comment by nickooolas** [comment]
Have been using Papertrail in my trials of Docker MQ. Works quite well, it starts up with the rest of the MQ sequence, even if it fails, it allows to know straight away what happened without having to go and dig through the Docker logs (which of course, don't reveal the contents of `AMQERR1.LOG` anyway.

I know some might be concerned about an external service logging, but I image a similar service might exist which can run locally without sending online, which can achieve the same task, but log it to the host directly for later review?

**Comment by parrobe** [comment]
Fixed in mq-container

This repo (mq-docker) is now deprecated and is being replaced by the [ibm-messaging/mq-container](https://github.com/ibm-messaging/mq-container) repo.
