### ISSUE TITLE
MQ container is not starting up

### ISSUE THREAD

**Issue by maverickuser** [ibm-messaging/mq-docker#3]
I am trying to run the MQ image (as default)  , the queue is not starting up.
sudo docker run \
  --env LICENSE=accept \
  --env MQ_QMGR_NAME=QM1 \
  --volume /var/example:/var/mqm \
  --publish 1414:1414 \
  --detach \
  ibmimages/mqadvanced

When i did a 
"docker inspect imageid"
In status it gives Exit code as 71

The msconfig gives everything as pass (i changed a setting in /etc/sysctl.conf and saved it)

The MQ is still not starting up. 

Can anyone please let me know what i am missing

Thanks

**Comment by arthurbarr** [comment]
Is there anything in the `docker logs` output?  One thought is the filesystem for `/var/example`.  MQ only supports certain filesystem types, so if the `/var/example` directory (in this case) were on an unsupported filesystem, it would fail - you should get a message about this in the logs though.

**Comment by maverickuser** [comment]
Name:        WebSphere MQ
Version:     8.0.0.2
Level:       p800-002-150303.DE
BuildType:   IKAP - (Production)
Platform:    WebSphere MQ for Linux (x86-64 platform)
Mode:        64-bit
O/S:         Linux 3.16.7-tinycore64
InstName:    Installation1
InstDesc:
Primary:     No
InstPath:    /opt/mqm
DataPath:    /var/mqm
MaxCmdLevel: 801
LicenseType: Developer
----------------------------------------
mqconfig: V3.7 analyzing Ubuntu 14.04.2 LTS settings for WebSphere MQ V8.0

System V Semaphores
  semmsl     (sem:1)  250 semaphores                     IBM>=32           PASS
  semmns     (sem:2)  0 of 32000 semaphores      (0%)    IBM>=4096         PASS
  semopm     (sem:3)  32 operations                      IBM>=32           PASS
  semmni     (sem:4)  0 of 128 sets              (0%)    IBM>=128          PASS

System V Shared Memory
  shmmax              18446744073692774399 bytes         IBM>=268435456    PASS
  shmmni              0 of 4096 sets             (0%)    IBM>=4096         PASS
  shmall              0 of 18446744073692774399 pages (0%)    IBM>=2097152      PASS

System Settings
  file-max            928 of 524288 files        (0%)    IBM>=524288       PASS

Current User Limits (root)
  nofile       (-Hn)  1048576 files                      IBM>=10240        PASS
  nofile       (-Sn)  1048576 files                      IBM>=10240        PASS
----------------------------------------
WebSphere MQ queue manager 'QM1' starting.
The queue manager is associated with installation 'Installation1'.
AMQ7017: Log not available.

Its saying "AMQ7017: Log not available." does it imply the same??

**Comment by arthurbarr** [comment]
Given that you seem to have a TinyCore Linux kernel, I'm guessing that you're using boot2docker.  Boot2docker uses the "rootfs" filesystem type for its root filesystem, including everything in `/var`.  MQ doesn't support this filesystem.  The solution is to put the volume elsewhere - for boot2docker, I'd recommend changing `/var/example` to `/mnt/sda1/example`.  Alternatively, you can omit the `-v` option completely, which will cause Docker to assign a valid volume - note that this then makes it harder then to check MQ's logs (which it writes to the volume).

A script in the Docker image is *supposed* to be checking this and giving an error message if the filesystem type is wrong, but doesn't seem to be happening - I will investigate.

This is not a supported filesystem type, and MQ is giving this (fairly unhelpful) message.

**Comment by maverickuser** [comment]
Thanks Arthur.
Yes, i am using boo2docker for Windows 7
I was able to get  the MQ Started by changing path  /var/example to /mnt/sda1/example.
I am trying to connect this MQ from a java client using MQ APis.
It giving Authetication error.i was assuming that by default its disabled
It will be really helpful if you can guide

**Comment by maverickuser** [comment]
Using MQSC command .Ran these two commands
ALTER QMGR CHLAUTH(DISABLED) CONNAUTH(' ')
REFRESH SECURITY TYPE(CONNAUTH) 

But still no suceess .

**Comment by arthurbarr** [comment]
FYI, I wrote a [blog entry](https://www.ibm.com/developerworks/community/blogs/messaging/entry/introducing_a_docker_image_for_mq_advanced_for_developers?lang=en) showing how to do this without turning CHLAUTH off completely (also see [Morag Hughson's recent blog post](https://www.ibm.com/developerworks/community/blogs/messaging/entry/getting_going_without_turning_off_mq_security?lang=en)).  Glad to hear you're up and running though.

**Comment by dreammeister** [comment]
Hi,

I had the same problem with volumes. I omitted the -v and got the QM running but I'm confused as to why this worked. Surely all volumes in the container are rootfs which MQ doesn't seem to like (couldn't find anything documented as to why MQ doesn't like these BTW). I also created my own image from scratch and ran into the same log issues despite installing MQ from OS up and creating the QM.

**Comment by suddip241277** [comment]
Hi All, 
Thanks all for the valuable informations
while i am running my mqadvance from boot2docker vm in my windows 7 system , I am getting the following error . I would be good if anyone can help me regarding this

docker@boot2docker:~$ sudo docker run \
>   --env LICENSE=accept \
>   --env MQ_QMGR_NAME=QM1 \
>    --publish 1414:1414 \
>   ibmcom/mqadvanced:MQv8
----------------------------------------
Name:        WebSphere MQ
Version:     8.0.0.2
Level:       p800-002-150303.DE
BuildType:   IKAP - (Production)
Platform:    WebSphere MQ for Linux (x86-64 platform)
Mode:        64-bit
O/S:         Linux 3.18.5-tinycore64
InstName:    Installation1
InstDesc:
Primary:     No
InstPath:    /opt/mqm
DataPath:    /var/mqm
MaxCmdLevel: 801
LicenseType: Developer
----------------------------------------
mqconfig: V3.7 analyzing Ubuntu 14.04.2 LTS settings for WebSphere MQ V8.0

System V Semaphores
  semmsl     (sem:1)  250 semaphores                     IBM>=32           PASS
  semmns     (sem:2)  0 of 32000 semaphores      (0%)    IBM>=4096         PASS
  semopm     (sem:3)  32 operations                      IBM>=32           PASS
  semmni     (sem:4)  0 of 128 sets              (0%)    IBM>=128          PASS

System V Shared Memory
  shmmax              18446744073692774399 bytes         IBM>=268435456    PASS
  shmmni              0 of 4096 sets             (0%)    IBM>=4096         PASS
  shmall              0 of 18446744073692774399 pages (0%)    IBM>=2097152
PASS

System Settings
  file-max            224 of 202141 files        (0%)    IBM>=524288       FAIL

Current User Limits (root)
  nofile       (-Hn)  1048576 files                      IBM>=10240        PASS
  nofile       (-Sn)  1048576 files                      IBM>=10240        PASS

ERROR: mqconfig returned a non-zero return code 

In th above log the "System Setting " part is failing , although I am not using -v option

**Comment by maverickuser** [comment]
Try this :
Configuration changes before creating container.
1)	Additional entries   required in linux kernel file (/etc/sysctl.conf)
fs.file-max = 524288
net.ipv4.tcp_keepalive_time = 300
        Save it 
$ sysctl –p

**Comment by suddip241277** [comment]
Hi 
 Thanks for valuable feedback , It is working fine now: gud luck

**Comment by suddip241277** [comment]
Hi 
It would be very helpful , If any one can help me with the next steps to configure the queue , Actually my intention to run a queue with in docker and doing the pub/sub by using that docker container with queue images

**Comment by maverickuser** [comment]
You can use MQ client to configure Queues like MQExplorer , MQ Java libraray etc

**Comment by suddip241277** [comment]
Thanks a lot , My intention to configure MQ Advance Telemetry(MQTT) in docker , Is anybody has done this before 


Thanks again 
Sudip
