### ISSUE TITLE
Re-run MQSC scripts at startup

### ISSUE THREAD

**Issue by arthurbarr** [ibm-messaging/mq-docker#33]
Currently, the MQSC configuration scripts are only run at the time of queue manager creation.  This means that the user needs to make configuration and administrative changes separately, for example through MQSC or PCF.  It would be better, and more intuitive, if an idempotent MQSC script could be used, and run every time.  For the most part, using the REPLACE keyword in MQSC will make it work even with existing resources.

A fix to this issue will allow configuration changes to be made by an updated Docker image.

**Comment by parrobe** [comment]
Completed in PR #52
