### ISSUE TITLE
AMQ6245 when using bind-mounted volumes on Docker for Mac

### ISSUE THREAD

**Issue by endnic** [ibm-messaging/mq-docker#34]
Hello everybody,

i cannot start up the default docker image on mac osx (el capitan) with following command:

`sudo docker run --env LICENSE=accept --env MQ_QMGR_NAME=QM1 --volume /Users/******/Desktop/dockerfiles/shared-folder:/var/mqm --publish 1414:1414 mq:8`
Same issue while start up version **9.0.0.0**

My log output looks like

> `AMQ6245: Error executing system call 'chown 1000:1000' on file
> '/var/mqm/shared/20496/libmqzsd.so' error '13'.
> AMQ6245: Error executing system call 'chown 1000:1000' on file
> '/var/mqm/shared/20496/libmqzsd_r.so' error '13'.
> AMQ6245: Error executing system call 'chown 1000:1000' on file
> '/var/mqm/shared/20497/libmqzsd.so' error '13'.
> AMQ6245: Error executing system call 'chown 1000:1000' on file
> '/var/mqm/shared/20497/libmqzsd_r.so' error '13'.
> total 12
> drwxrwsr-x  2 mqm mqm   68 Oct 18 12:06 config
> drwxrwsr-x  3 mqm mqm  102 Oct 18 12:06 conv
> drwxrwsrwx 17 mqm mqm  578 Oct 18 12:47 errors
> drwxrwsr-x  2 mqm mqm   68 Oct 18 12:06 exits
> drwxrwsr-x  2 mqm mqm   68 Oct 18 12:06 exits64
> drwxrwsr-x  3 mqm mqm  102 Oct 18 12:06 log
> -rw-rw-r--  1 mqm mqm  637 Oct 18 12:06 mqclient.ini
> drwxrwsr-x  5 mqm mqm  170 Oct 18 12:06 mqft
> -rw-rw-r--  1 mqm mqm 2604 Oct 18 12:06 mqs.ini
> drwxrwsr-x  4 mqm mqm  136 Oct 18 12:06 qmgrs
> -rw-rw-r--  1 mqm mqm 1941 Oct 18 12:06 service.env
> drwxrwsr-x  4 mqm mqm  136 Oct 18 12:06 shared
> drwxrwsr-x  4 mqm mqm  136 Oct 18 12:06 sockets
> drwxrwsrwx  2 mqm mqm   68 Oct 18 12:06 trace
> *
> Name:        WebSphere MQ
> Version:     8.0.0.4
> Level:       p800-004-151022.DE
> BuildType:   IKAP - (Production)
> Platform:    WebSphere MQ for Linux (x86-64 platform)
> Mode:        64-bit
> O/S:         Linux 4.4.20-moby
> InstName:    Installation1
> InstDesc:
> Primary:     Yes
> InstPath:    /opt/mqm
> DataPath:    /var/mqm
> MaxCmdLevel: 802
> LicenseType: Developer
> *
> WebSphere MQ queue manager 'QM1' starting.
> The queue manager is associated with installation 'Installation1'.
> AMQ7017: Log not 

I don't know, what i'm doing wrong. Can anybody help me? Thanks in advance.

**Comment by arthurbarr** [comment]
This is an issue around file permissions.  This can get (even more) complicated in environments like Docker for Mac, as you're actually sharing the directory on your Mac with a Linux VM, which is then sharing it with the container.  I'll have to get back to you on this, but for now, you could always use a named Docker volume, for example:

```
docker volume create --name foo
docker run --env LICENSE=accept --env MQ_QMGR_NAME=QM1 --volume foo:/var/mqm --publish 1414:1414 mq:8
```

**Comment by erikwilliamsa** [comment]
I'm not sure if this is the same issue, because I'm not seeing the permissions issues,  but I'm getting the AMQ7017 whenever I attempt to run the image with a `/Users` filesystem.

Note, the foo solution works fine for me as well.

```
☁  V8  docker run \
  --env LICENSE=accept \
  --env MQ_QMGR_NAME=QM1 \
  --volume /Users/******/docker/mq/ibm/v8:/var/mqm \
  --publish 1414:1414 \
   mq-dev-8
total 12
drwxrwsr-x 2 mqm mqm   68 Dec 30 15:49 config
drwxrwsr-x 3 mqm mqm  102 Dec 30 15:49 conv
drwxrwsrwx 5 mqm mqm  170 Dec 30 15:49 errors
drwxrwsr-x 2 mqm mqm   68 Dec 30 15:49 exits
drwxrwsr-x 2 mqm mqm   68 Dec 30 15:49 exits64
drwxrwsr-x 2 mqm mqm   68 Dec 30 15:49 log
-rw-rw-r-- 1 mqm mqm  637 Dec 30 15:49 mqclient.ini
drwxrwsr-x 5 mqm mqm  170 Dec 30 15:49 mqft
-rw-rw-r-- 1 mqm mqm 2475 Dec 30 15:49 mqs.ini
drwxrwsr-x 3 mqm mqm  102 Dec 30 15:49 qmgrs
-rw-rw-r-- 1 mqm mqm 1941 Dec 30 15:49 service.env
drwxrwsr-x 4 mqm mqm  136 Dec 30 15:49 shared
drwxrwsr-x 3 mqm mqm  102 Dec 30 15:49 sockets
drwxrwsrwx 2 mqm mqm   68 Dec 30 15:49 trace
----------------------------------------
Name:        WebSphere MQ
Version:     8.0.0.4
Level:       p800-004-151022.DE
BuildType:   IKAP - (Production)
Platform:    WebSphere MQ for Linux (x86-64 platform)
Mode:        64-bit
O/S:         Linux 4.4.39-moby
InstName:    Installation1
InstDesc:
Primary:     Yes
InstPath:    /opt/mqm
DataPath:    /var/mqm
MaxCmdLevel: 802
LicenseType: Developer
----------------------------------------
Checking filesystem...
The tests on the directory completed successfully.
----------------------------------------
WebSphere MQ queue manager created.
Directory '/var/mqm/qmgrs/QM1' created.
The queue manager is associated with installation 'Installation1'.
AMQ7017: Log not available.
WebSphere MQ queue manager 'QM1' starting.
The queue manager is associated with installation 'Installation1'.
AMQ7017: Log not available.
----------------------------------------
WebSphere MQ queue manager 'QM1' starting.
The queue manager is associated with installation 'Installation1'.
AMQ7017: Log not available.

```

**Comment by parrobe** [comment]
This repo (mq-docker) is now deprecated and is being replaced by the [ibm-messaging/mq-container](https://github.com/ibm-messaging/mq-container) repo. Please try this new repo and see if you continue to experience the problem listed here. If you do please raise a new issue on the new repo.
