### ISSUE TITLE
FixPack

### ISSUE THREAD

**Issue by davidkarlsen** [ibm-messaging/mq-docker#4]
Should it be patched with the latest FP?

**Comment by dnwe** [comment]
@davidkarlsen this will happen automatically as the MQ Advanced for Developers product that the Docker image is based upon is periodically refreshed with the MQ Fixpack changes applied. Currently the image is at 8.0.0.2 level, and will be updated to 8.0.0.3 as soon as the MQ Advanced for Developers download is available.
