### ISSUE TITLE
Running without root access

### ISSUE THREAD

**Issue by mbpolan** [ibm-messaging/mq-docker#40]
Hi,

Is there any way to run this image if the container doesn't allow root access? Reason being is that I'm attempting to deploy the mq:8 image in OpenShift which normally doesn't allow containers to gain privileged rights. I end up with a bunch of permission complaints and this message among others:

`AMQ6240: You must be an operating system superuser to run this command.`

Thanks!

**Comment by arthurbarr** [comment]
I don't think so.  When you run a container based on the sample MQ Docker image, it first tries to set up `/var/mqm` with all the necessary files.  These files are typically created as part of an MQ installation, but in the Docker case, we almost always want to use a Docker volume, which is empty by default.  MQ requires the files in `/var/mqm` to be owned by the `mqm` user, which means it has to perform a `chown` to change the ownership, which requires root access.

Once the files in `/var/mqm` have been set up, the queue manager itself runs as the `mqm` user.  Currently, the Docker-specific health checks from the sample run as the `root` user, but that could be changed.

I think you can still run in OpenShift by [https://docs.openshift.com/enterprise/3.0/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile](editing the security context) (or perhaps creating a new one).

**Comment by mbpolan** [comment]
Thanks for the reply! I had a suspicion that would be the case. I'm aware of the OpenShift security context approach, but unfortunately I don't have the necessary permissions to enable that in our private OSE setup to test this out.

I'm ok with closing this issue given the situation.
