### ISSUE TITLE
Lack of MQ output in Docker logs makes debugging MQ startup errors difficult

### ISSUE THREAD

**Issue by parrobe** [ibm-messaging/mq-docker#43]
While attempting to debug what was causing issue #42 i found it incredibly difficult to see what had gone wrong with a Queue Manager when i started the container and it immediately died.

Eventually to debug it i had mount a the MQ Data directory in a volume, run the container to recreate and then look inside that volume for the error. 

What would be useful is that if, on startup an error is detected starting the Queue Manager (or even when the container ends) the last 30 lines of the `AMQERR01.LOG` in both the `/var/mqm/errors` folder and the `/var/mqm/qmgrs/<QM Name>/errors` was printed out to stdout and so picked up in the docker logs.

**Comment by dnwe** [comment]
Related to #26

**Comment by parrobe** [comment]
Fixed in mq-container

**Comment by parrobe** [comment]
This repo (mq-docker) is now deprecated and is being replaced by the [ibm-messaging/mq-container](https://github.com/ibm-messaging/mq-container) repo. Please try this new repo and see if you continue to experience the problem listed here. If you do please raise a new issue on the new repo.
