### ISSUE TITLE
Example customization with OS user doesn't work

### ISSUE THREAD

**Issue by prestona** [ibm-messaging/mq-docker#53]
The example Dockerfile for creating your own image with a OS user / password doesn't work.
```dockerfile
FROM mq
RUN useradd alice -G mqm && \
    echo alice:passw0rd | chpasswd
COPY 20-config.mqsc /etc/mqm/
```

It appears that it's broken by `mq-dev-config.sh` which configures an admin user that has a UID that clashes with the one generated for `alice`.

Here's an alternative that works by explicitly specifying the UID for alice in a range outside those used by the scripts:

```dockerfile
FROM mq
RUN useradd -N -G mqm -u 5001 alice && \
    echo alice:passw0rd | chpasswd
COPY 20-config.mqsc /etc/mqm/
```

**Comment by parrobe** [comment]
Thanks, we're currently deciding how to fix this or whether to change the example. 
Given that we now create 2 users by default in the `mq-dev-config.sh` file we may no longer need an example that creates a user.

**Comment by parrobe** [comment]
Hi @prestona - We've just merged a Pull Request that should fix this issue. Could you ensure you have the latest master/release (v3.0) and try to recreate the problem.

**Comment by parrobe** [comment]
Hi @prestona I'll close this issue as I've manually verified. If you're still seeing the issue then feel free to reopen this one or create a new one.
