### ISSUE TITLE
app user missing role to access QM1

### ISSUE THREAD

**Issue by dtanner** [ibm-messaging/mq-docker#54]
I don't know much about MQ, so let me know if I missed something that's obvious...

I wasn't able to successfully connect to the queue manager with a standalone MQ java client until I added the `inq` authority to the `app` user for `QM1`.

e.g. Running the container using the developer defaults:
```
docker run \
  --env LICENSE=accept \
  --env MQ_QMGR_NAME=QM1 \
  --publish 1414:1414 \
  --publish 9443:9443 \
  --detach \
  ibmcom/mq
```

The following code:
```java
import com.ibm.msg.client.jms.JmsConnectionFactory;
import com.ibm.msg.client.jms.JmsConstants;
import com.ibm.msg.client.jms.JmsFactoryFactory;
import com.ibm.msg.client.wmq.WMQConstants;

import javax.jms.*;

import static com.ibm.msg.client.wmq.common.CommonConstants.*;

public class Client {
    public static void main(String[] args) throws Exception {

        JmsFactoryFactory ff = JmsFactoryFactory.getInstance(JmsConstants.WMQ_PROVIDER);
        JmsConnectionFactory factory = ff.createConnectionFactory();

        factory.setStringProperty(WMQ_CHANNEL, "DEV.APP.SVRCONN");
        factory.setStringProperty(WMQ_HOST_NAME, "localhost");
        factory.setIntProperty(WMQ_PORT, 1414);
        factory.setStringProperty(WMQ_QUEUE_MANAGER, "QM1");
        factory.setIntProperty(WMQ_CONNECTION_MODE, WMQConstants.WMQ_CM_CLIENT);

        Connection connection = factory.createConnection("app", "");
        connection.start();

        Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
        Queue queue = session.createQueue("DEV.QUEUE.1");
        MessageProducer producer = session.createProducer(queue);
        TextMessage outMessage = session.createTextMessage("poo poo");
        producer.send(outMessage);
    }

}
```

...results in an error at the createConnection method with the `2035` error code.  The queue manager logs at `/var/mqm/qmgrs/QM1/errors` showed this detail:
`AMQ8077: Entity 'app' has insufficient authority to access object 'QM1'.`

The fix for me was to execute this in the container:
`setmqaut +inq -m QM1 -p app`

IMO this authority should be granted by default in the container in the developer defaults situation.  If you agree, can you add that to the image?  If not, can you give some guidance on the suggested solution?  Thanks.

**Comment by dtanner** [comment]
p.s. Just noticed that similar-looking code also needs the `inq` role on `DEV.QUEUE.*` to be able to read messages from the queues.

**Comment by dtanner** [comment]
just read a little more, and it seems like the problem could be a user/role mapping issue.  i.e. it appears that the mqclient group has the necessary permissions, but for things to work for me, I had to explicitly give the user the permissions.

**Comment by parrobe** [comment]
The mqclient group does not have the `INQ` permission for the Queue Manager only `connect`. Your Java code looks fine so i believe it was a mistake on my part and misunderstanding about what each applications need (permissions wise) to connect.

**Comment by dtanner** [comment]
closing... #56 should take care of this.
