### ISSUE TITLE
Issue while creating docker mq image 

### ISSUE THREAD

**Issue by vassu9611** [ibm-messaging/mq-docker#62]
MQServer/lap/jre/ibm-java-x86_64-80/jre/lib/ibmjssefw.jar
MQServer/lap/jre/ibm-java-x86_64-80/jre/lib/healthcenter.properties
MQServer/lap/jre/ibm-java-x86_64-80/jre/plugin/
MQServer/lap/jre/ibm-java-x86_64-80/jre/plugin/desktop/
MQServer/lap/jre/ibm-java-x86_64-80/jre/plugin/desktop/sun_java.png
MQServer/lap/jre/ibm-java-x86_64-80/jre/plugin/desktop/sun_java.desktop
MQServer/lap/jre/ibm-java-x86_64-80/notices.txt
MQServer/MQSeriesMan-9.0.0-0.x86_64.rpm
MQServer/MQSeriesFTAgent-9.0.0-0.x86_64.rpm

Licensed Materials - Property of IBM

 5724-H72

 (C) Copyright IBM Corporation 1993, 2016

US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.

Agreement accepted:  Proceed with install.

**error: File not found by glob: MQSeriesWeb*.rpm**

The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive   && apt-get update -y   && apt-get install -y --no-install-recommends     bash     bc     coreutils     curl     debianutils     findutils     gawk     grep     libc-bin     lsb-release     mount     passwd     procps     rpm     sed     tar     util-linux   && mkdir -p /tmp/mq   && cd /tmp/mq   && curl -LO $MQ_URL   && tar -zxvf ./*.tar.gz   && groupadd --gid 1000 mqm   && useradd --uid 1000 --gid mqm mqm   && usermod -G mqm root   && cd /tmp/mq/MQServer   && ./mqlicense.sh -text_only -accept   && rpm -ivh --force-debian $MQ_PACKAGES   && /opt/mqm/bin/setmqinst -p /opt/mqm -i   && rm -rf /tmp/mq   && rm -rf /var/lib/apt/lists/*   && echo "mq:$(dspmqver -b -f 2)" > /etc/debian_chroot   && rm -rf /var/mqm   && sed -i 's/PASS_MAX_DAYS\t99999/PASS_MAX_DAYS\t90/' /etc/login.defs   && sed -i 's/PASS_MIN_DAYS\t0/PASS_MIN_DAYS\t1/' /etc/login.defs   && sed -i 's/password\t\[success=1 default=ignore\]\tpam_unix\.so obscure sha512/password\t[success=1 default=ignore]\tpam_unix.so obscure sha512 minlen=8/' /etc/pam.d/common-password' returned a non-zero code: 1

**Comment by vassu9611** [comment]
same with both images 
> IBM_MQ_9.0.0.0_LINUX_X86-64.tar.gz ---- > mq-docker-2.0.0
>WS_MQ_V8.0.0.4_LINUX_ON_X86_64_IM.tar.gz --- > mq-docker

**Comment by vassu9611** [comment]
docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

**Comment by parrobe** [comment]
The `MQSeriesWeb*.rpm` package is not available in MQ 9 or MQ 8 (only MQ 9.0.1). You either need to update to 9.0.1 or remove this package from the list of packages to install for these versions.

**Comment by vassu9611** [comment]
Sure  will try with 9.0.2..

Thanks,
Parsa

**Comment by vassu9611** [comment]
Install went  good, but seeing warning:
WARNING: System settings for this system do not meet recommendations for this product
         See the log file at "/tmp/mqconfig.1207.log" for more information

I Don't see that file is created while image build.

Any Suggestions?

Thanks,
Parsa

**Comment by vassu9611** [comment]
Got it.. that error is on docker host as the file is written to container.

After container creation I can see that file in that location.

Thanks,
Parsa
