### ISSUE TITLE
MQ Docker for Windows for Docker (native, not Toolbox)

### ISSUE THREAD

**Issue by QAnders** [ibm-messaging/mq-docker#63]
Is there any container available that runs on Docker for Windows natively?

**Comment by arthurbarr** [comment]
No, that's not something we've heard a requirement for so far, but we're always interested in such things.  Are there any specific use cases you're interested in?

**Comment by QAnders** [comment]
I am working as a IBM Business Partner (consultant) and I run a lot of DataPower and API Connect. Previously I was using VMware but we have now moved to use only Docker as Dev tools.
I run on Windows and have DataPower Docker which I'd need to connect to MQ. As VMware and Docker don't run at the same time on Windows (Hyper-V) I don't have any MQ instance now.
I don't want to install MQ locally as this should be a shared (or possible to share) dev. instance.

Ideally I'd like the MQ Appliance VMware on Docker but that might be asking too much... ;)

**Comment by QAnders** [comment]
Never mind... I got the one on https://hub.docker.com/r/ibmcom/mq/ working!

I can run it as a Linux container and I just had to remove the --volume mapping to get it running.
