### ISSUE TITLE
Is it possible to use a CipherSpec other than TLS_RSA_WITH_AES_256_GCM_SHA384 ?

### ISSUE THREAD

**Issue by kimptoc** [ibm-messaging/mq-docker#64]
Having trouble connecting using the sample MQ Java apps from an Oracle JDK on Windows - getting JMSCMQ0001 / MQCC_FAILED / MQRC_UNSUPPORTED_CIPHER_SUITE, reason 2400.

I presume the issue with the client configuration - I can connect MQ explorer to my MQ server ok.

Just wondering if using a different cipher spec would help.

Thanks in advance,
Chris

**Comment by parrobe** [comment]
What Cipher Suite are you setting on your MQ java App and what CipherSpec are you setting on your MQ Channel?

**Comment by kimptoc** [comment]
Hmm - you need to specify both?

Working with the MQ Client SimplePubSub example (connected ok before I enabled SSL).

The only part I have changed in the code is to add this setting in bit that sets properties on the JmsConnectionFactory
```
      cf.setStringProperty(WMQConstants.WMQ_SSL_CIPHER_SUITE, "SSL_RSA_WITH_AES_256_GCM_SHA384");
```

And added these system properties when I run it
```
-Djavax.net.ssl.trustStore=c:\path\to\keystore.jks -Djavax.net.ssl.keyStore=c:\path\to\keystore.jks -Djavax.net.ssl.trustStorePassword=xx -Djavax.net.ssl.keyStorePassword=xx 
```

Error is:
```
com.ibm.mq.MQException: JMSCMQ0001: WebSphere MQ call failed with compcode '2' ('MQCC_FAILED') reason '2400' ('MQRC_UNSUPPORTED_CIPHER_SUITE').
FAILURE
```

Just downloaded the IBM JDK 8(6.4.1) and it fails in a similar way.

MQ Explorer works with the same keystore and this CipherSpec TLS_RSA_WITH_AES_256_GCM_SHA384

Thanks.

**Comment by parrobe** [comment]
> Hmm - you need to specify both?

You need to have enabled TLS on the channel by setting the `SSLCIPH` attribute on the channel you want to be TLS enabled to a specific CipherSpec. Once set it will only accept TLS connections where the client connecting uses the matching CipherSpec. For Java Clients you need to make sure the CipherSuite used matches the CipherSpec on the channel. [See here for a CipherSpec to CipherSuite conversion guide.](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.dev.doc/q113220_.htm)

Additionally, the CipherSuite ` SSL_RSA_WITH_AES_256_GCM_SHA384` is protected and needs to be activated by enabling the 'unrestricted' policy files in the JRE. [You can see details how to do this here.](https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/sdkpolicyfiles.html)

Other than that looking at the code snippits you've given me i can't see anything wrong with them. Do the Queue Manager logs or your java client logs show anything?

- For Queue Manager logs on your docker container running the Queue Manager go to `/var/mqm/qmgrs/<Queue Manager Name>/errors/AMQERR01.LOG`
- For Client logs on your machine you're running the client go to the data root (found by doing a `dspmqver` and then look at the AMQERR01.LOG file in the errors directory. Default is /var/mqm/errors on Unix and `C:\ProgramData\IBM\MQ\errors` on windows.

To answer your question in the title of this issue. Yes you can use any CipherSpec or CipherSuite that MQ supports.

**Comment by kimptoc** [comment]
Thanks for the detailed response, will have a play on Monday .  Have a great weekend

**Comment by kimptoc** [comment]
From my perspective, this issue can be closed.  Many thanks.
