### ISSUE TITLE
Default SSL config (mutual and other) - any plans to include it as an option in the repo?

### ISSUE THREAD

**Issue by kimptoc** [ibm-messaging/mq-docker#67]
Hi,

I have done a test setup based on this image to secure the server side:
https://github.com/kimptoc/ibmmq-with-ssl-test/tree/master/mq-with-ssl

Would you be interested in a pull request to put that into this repo?  E.G. via an option.  Obviously for testing only :)

I'd like to extend it to include mutual SSL, client needs a certificate too.  However I am struggling to get my head around how that is configured, on the server side.

Does it go into the same keystore and it knows which to use? Or is there a different setting for client keystores?

Many Thanks in advance for any tips.
Chris

**Comment by parrobe** [comment]
Hi @kimptoc 
We already have a method for users of this sample to supply a keystore to use for securing their Queue Manager. See the `MQ_TLS_KEYSTORE` [environment variable](https://github.com/ibm-messaging/mq-docker#list-of-all-environment-variables-supported-by-this-image)

> Does it go into the same keystore and it knows which to use? Or is there a different setting for client keystores?

In IBM MQ all certificates (Both personal and trusted) go into a single keystore which is of type CMS. This differs from say java which has a trust store and a keystore. The default keystore used by MQ Queue Managers lives under `<MQ Data Root>/qmgrs/<QM Name>/ssl/key.kdb`

To trust a client certificate it is slightly different depending on whether the client uses self signed or ca signed certificates:
- For Self-Signed the Client must supply a copy of it's public certificate and this must be added into the Queue Manager's keystore
- For Ca-Signed the client's signer public certificate and chain above must be added into the Queue Manager's keystore. For example if the certificate chain is `Client->Intermediary CA-> Root CA`. Then the Queue Manager's keystore must contain both the Intermediary and Root Ca public certificates. You can also add the Client's public certificate but this is not necessary.

To add a client certificate to the Queue Manager's keystore you can use the `runmqakm` or `runmqckm` commands and the `-cert -add` verbs.

**Comment by kimptoc** [comment]
Many thanks for that.

**Comment by parrobe** [comment]
@kimptoc Would it be ok to close this ticket or is there anything else we can help you with?

**Comment by kimptoc** [comment]
yes, thats fine.  Thanks again.
