### ISSUE TITLE
Adding DEVMODE to mq8

### ISSUE THREAD

**Issue by michaeljquinn** [ibm-messaging/mq-docker#70]
the dev mode capability is missing from the mq8 branch, is it possible to merge the Dockerfile from master to the mq8 branch (leaving out the mq9 specifics)
thanks

**Comment by parrobe** [comment]
Hi @michaeljquinn the mq8 branch is part of our LTS stream. This means that new development items (which includes the dev mode) will not be added.

You're welcome to implement these in your own git repo, however we won't be backporting the changes. This is the same policy that is applied to features added to IBM MQ.
