### ISSUE TITLE
Trying adding multiple listeners

### ISSUE THREAD

**Issue by mhermosi** [ibm-messaging/mq-docker#81]
Hi,

I am trying adding multiple listeners and multiple MQ Managers each time I try MQ stop working.
Also do you know if I can add Mediation Flow I want to create an env of 3 QMGR 2 zones and a Broker with mediation flow.

Best,

**Comment by parrobe** [comment]
Hi @mhermosi ,

Adding extra listeners into the docker container shouldn't be a problem. When defining the extra listener you need to make sure that the port you define it with is not already used (by default only `1414` & `9443` are already in use) and you also need to make sure you have started the docker container exposing this port. In the Dockerfile we automatically do this using `EXPOSE 1414 9443` on line 96, however you can also do this by running your container using the `--publish` or `-p` argument.

For multiple Queue Managers, generally in a docker environment you would have a single Queue Manager in each container. If you needed multiple Queue Managers you would create multiple containers. If you do want to add multiple Queue Managers into a single container then that shouldn't be a problem. For the sample in this Github repository you'll need to note that to keep the container running we monitor a single Queue Manager's health and when that Queue Manager stops we end the Queue Manager. If you have 5 Queue Managers on your container and one goes down then the whole container could stop if that one container is the one we monitor. To stop this you would need to adjust the `mq-monitor-qmgr.sh` script to monitor all of  your Queue Managers and only stop when all of them end.

Finally, I'm afraid i don't know what a **Mediation Flow** is. You can expand on this Sample by cloning the repository or creating a new Dockerfile with `FROM ibmcom/mq`, you can then add any new features or functionality you need, or modify the sample to meet your requirements.

**Comment by parrobe** [comment]
Hi @mhermosi - Hopefully i answered your question. If not please feel free to reopen this issue and request further information.

**Comment by FatihaBiga** [comment]
@parrobe you said that we can create multiple Queue Manager in one container,but how we will do that if the container takes the MQ_QMGR_NAME in arguments?

**Comment by arthurbarr** [comment]
Running multiple queue managers in a single container is not something we'd recommend, for the reasons @parrobe mentioned.  If you do want to do this, you will need to fork the code, and change things like the use of the `MQ_QMGR_NAME` environment variable yourself.

**Comment by mhermosi** [comment]
Sorry for the late answer. I've been out a while. yes you answered and Thanks, I did not realized the idea at the beginning of having 1 QMGR per container but I got the concept now. 

Thanks again
