### ISSUE TITLE
update readme.md

### ISSUE THREAD

**Issue by ompraash** [ibm-messaging/mq-docker#91]
In documentation [https://github.com/ibm-messaging/mq-docker/blob/master/README.md](url)
please add additional note for section "Running with the default configuration" for the example on running the docker image on mac.

Current 
`--volume /var/example:/mnt/mqm \`

New
`--volume /private/var/example:/mnt/mqm \`

This prevents users from adding additional mounts in docker.

**Comment by parrobe** [comment]
Hi @ompraash - Could you elaborate a little bit please.

Why does changing the mount directory from `/var/example` to `/private/var/example` stop users from adding additional mounts in docker?

**Comment by parrobe** [comment]
Hi @ompraash - It's been a month without an answer to our question. We've done some googling but can't find anything that references users being able to add additional mounts and using /private/var/example would prevent that.

I'll close this issue as we haven't heard from you but if you do return to answer the question then please feel free to re-open this issue.
