### ISSUE TITLE
AMQP-MQ Lite configuration

### ISSUE THREAD

**Issue by michaeljquinn** [ibm-messaging/mq-docker#93]
More of an enhancement really - and maybe a question elsewhere
I altered the dockerfile (MQ8) to install the AMQP and samples rpms, worked like a charm, but I am really struggling with getting the AMQP connections to work - the authentications just dont work
I am using node v6 with the samples 
If anyone has a AMQP config that works, much appreciated, heres my snippet
Trying to use the "app" user

*****************************************************************
START SERVICE(SYSTEM.AMQP.SERVICE)
SET CHLAUTH(SYSTEM.DEF.AMQP) TYPE(ADDRESSMAP) ADDRESS(*) USERSRC(CHANNEL) CHCKCLNT(REQUIRED)
ALTER CHANNEL(SYSTEM.DEF.AMQP) CHLTYPE(AMQP) MCAUSER(app)
REFRESH SECURITY TYPE(CONNAUTH)
START CHANNEL(SYSTEM.DEF.AMQP)
DISPLAY CHSTATUS(SYSTEM.DEF.AMQP) CHLTYPE(AMQP)
* mqlite topic
DEFINE TOPIC('HSI.DEV.MQLITE.TOPIC') TOPICSTR('mqlite/') REPLACE

**Comment by matthew1001** [comment]
Can you look in /var/mqm/qmgrs/QMNAME/errors/AMQERR01.LOG and see if there's a specific security-related message in there?

Also, have you authorised the user 'app' to pub, sub and connect to the HSI.DEV.MQLITE.TOPIC?

**Comment by parrobe** [comment]
It should also be noted that the MQ 8 dockerfile and scripts do not create the developer defaults users (admin & app) so you would need to also make sure you scripts have created the user app and provided them with the authorities that Matthew mentions above.

**Comment by parrobe** [comment]
Hi @michaeljquinn - It's been nearly two months since we've heard from you. I'll close this issue but if you would like to continue the discussion then please do reopen it with further information/questions relating to this issue
